<div class="quickview-button__wrapper">
	<a class="icon-search <?php echo $block->getButtonClasses() ?>"
	   data-quickview-url="<?php echo $block->getQuickViewUrl() ?>"
	   aria-hidden="true"
	>
	    <?php echo $block->getButtonText()  ?>
	</a>
</div>
<div id="js-quickview-popup" style="display: none">
	<iframe style="margin-top: 2vh" width="100%" height="500px" frameborder="0" src="<?php echo $block->getQuickViewUrl() ?>"></iframe>
</div>