<script>
    requirejs([
            'jquery',
            'Magento_Ui/js/modal/modal'
        ],
        function($, modal) {
            $(document).ready(function() {
                $('.siyu-quickview').bind('click', function() {
                    $('#js-quickview-popup').modal({
                        title: 'QuickView',
                        autoOpen: true,
                        responsive: true,
                        buttons: [{
                            text: 'close',
                            class: '.siyu-quickview',
                            click: function() {
                                this.closeModal();
                            } //handler on button click
                        }]
                    });
                });
            });
        }
    );
</script>